#include "main.h"
#include <stdio.h>

extern UART_HandleTypeDef huart1;

/*
 * Retarget standard output to UART1.
 *
 * The C standard library uses the low-level _write() system call whenever
 * functions such as printf(), puts(), or fprintf(stdout, ...) need to output
 * formatted characters.
 *
 * By providing our own _write() implementation, the linker uses this function
 * instead of the default stub supplied by the embedded C library. The formatted
 * output generated by printf() is therefore passed to this function as a byte
 * buffer and transmitted through UART1.
 *
 * file: Output stream identifier, typically 1 for stdout and 2 for stderr.
 * ptr:  Pointer to the formatted character buffer.
 * len:  Number of bytes to transmit.
 */
int _write(int file, char *ptr, int len)
{
    HAL_UART_Transmit(&huart1, (uint8_t *)ptr, len, HAL_MAX_DELAY);
    return len;
}